POST https://127.0.0.1/users HTTP/1.1
content-type:application/json

{
    "login":"bob",
    "password":"1244",
    "roleId":"c6c0044b-4bdf-4c3e-b71b-941cc7dcfb8f"
}
###

GET https://127.0.0.1/users HTTP/1.1

###

POST https://127.0.0.1/roles HTTP/1.1
content-type:application/json

{
    "name":"admin"
}
###

GET https://127.0.0.1/users HTTP/1.1