POST https://127.0.0.1/books HTTP/1.1
content-type:application/json

{
    "title":"testbook1"
}

###

GET https://127.0.0.1/books HTTP/1.1

###

POST https://127.0.0.1/users HTTP/1.1
content-type:application/json

{
    "login":"admin2",
    "role":"admin"
}
###

GET https://127.0.0.1/users HTTP/1.1

###

POST https://127.0.0.1/posts HTTP/1.1
content-type:application/json

{
    "title":"post",
    "description":"post description",
    "userId":"54bb0377-c48f-4798-9ac1-088940fe7875"
}
###

GET https://127.0.0.1/posts HTTP/1.1

###

POST https://127.0.0.1/profiles HTTP/1.1
content-type:application/json

{
    "city":"Odesa",
    "detail_info":"more info",
    "userId":"54bb0377-c48f-4798-9ac1-088940fe7875"
}
###

GET https://127.0.0.1/profiles HTTP/1.1